export const ARCHITECT_READS_PER_PHASE = 20;
export const ARCHITECT_RANGE_READS_PER_PHASE = 30;
export const ARCHITECT_SEARCHES_PER_PHASE = 20;

export const ARCHITECT_REVIEW_READS_PER_PHASE = 32;
export const ARCHITECT_REVIEW_RANGE_READS_PER_PHASE = 48;
export const ARCHITECT_REVIEW_SEARCHES_PER_PHASE = 32;
