import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
const task='.superpowers/sdd/2026-09-11-p6-completion/task8-3-lsp',out=task+'/acceptance-final-20260913';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,'')),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),norm=p=>p.replaceAll('\\','/');
const changedTests=['runner-v2/test/bounded-output-spool.test.ts','runner-v2/test/evidence-continuation.test.ts','runner-v2/test/streaming-process-session-runtime.test.ts'];
const walk=p=>fs.readdirSync(p,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(p,e.name)):[norm(path.join(p,e.name))]);
function gate(id,expected=0){const r=read(out+'/'+id+'/terminal.json');if(r.exitCode!==expected||!r.inputsUnchanged||r.signal)throw new Error('Unsatisfied gate '+id);const inputs=read(out+'/'+id+'/inputs-after.json');const drift=inputs.filter(e=>e.path.startsWith('runner-v2/')&&sha(e.path)!==e.sha256).map(e=>e.path);if(drift.some(p=>!changedTests.includes(p)))throw new Error('Unexpected final input drift '+id+': '+drift);const log=fs.readFileSync(out+'/'+id+'/stdout.log','utf8');const counts=Object.fromEntries([...log.matchAll(/^# (tests|pass|fail|cancelled|skipped) (\d+)$/gm)].map(m=>[m[1],Number(m[2])]));return {id,receipt:r,counts,driftReplacedByCompleteFileGate:drift,receiptSha256:sha(out+'/'+id+'/terminal.json')};}
const windows=['windows-mcp-shared','windows-lsp-acceptance','windows-affected-acceptance','cli-complete-recheck','windows-linked-complete'].map(id=>gate(id,id==='windows-affected-acceptance'?1:0));
const graph=windows[2];if(graph.counts.fail!==1||graph.counts.cancelled!==0)throw new Error('Unexpected graph failures');const graphLog=fs.readFileSync(out+'/windows-affected-acceptance/stdout.log','utf8');const failures=graphLog.split(/\r?\n/).filter(l=>/^not ok /.test(l));if(failures.length!==1||!failures[0].includes('CLI statically validates extension closure without evaluating live tool declarations'))throw new Error('Graph failure not superseded by CLI complete recheck');
const statics=['typecheck-acceptance','eslint-acceptance','diff-check-acceptance'].map(id=>gate(id));
const linuxFirst=read(out+'/linux-lsp-shared-acceptance/tmp-evidence/task83-linux-receipts.json'),linuxFinal=read(out+'/linux-shared-final/tmp-evidence/task83-linux-receipts.json');if(linuxFirst.slice(0,3).some(r=>r.exitCode!==0)||linuxFinal.length!==2||linuxFinal.some(r=>r.exitCode!==0))throw new Error('Linux command gate failed');
const linuxReceipt=read(out+'/linux-shared-final/terminal.json');if(linuxReceipt.exitCode!==0||!linuxReceipt.inputsUnchanged||!linuxReceipt.removed||!linuxReceipt.absenceVerified)throw new Error('Linux ownership gate failed');
const linuxSourceInputs=read(out+'/linux-lsp-shared-acceptance/inputs-after.json');const linuxDrift=linuxSourceInputs.filter(e=>sha(e.path)!==e.sha256).map(e=>norm(e.path));if(linuxDrift.some(p=>!changedTests.includes(p)))throw new Error('Linux positive family input drift');
const resources=read(out+'/resource-accounting.json');if(resources.unresolved.length)throw new Error('Resource gate unresolved');
const baseline=read(out+'/baseline.json');const protectedDrift=baseline.protectedFiles.filter(e=>!fs.existsSync(e.path)||sha(e.path)!==e.sha256);if(protectedDrift.length)throw new Error('Protected inputs changed');if(!fs.readFileSync(out+'/index.txt').equals(execFileSync('git',['ls-files','--stage'])))throw new Error('Index changed before acceptance');
const material=read(out+'/causal-evidence-audit.json');for(const p of material.proofs){if(p.red.exitCode!==1||p.red.parseOrLoadError||p.red.failedTests.length===0||p.green.exitCode!==0)throw new Error('Invalid historical causal proof '+p.id);}
const refresh=read(out+'/causal-refresh-results.json');if(refresh.length!==4||refresh.some(p=>p.red.exitCode!==1||p.green.exitCode!==0||p.originalHash!==p.restoredHash||sha(p.file)!==p.restoredHash))throw new Error('Current causal proof failed');
const linked=read(out+'/linked-fixture-reverse-result.json');if(!linked.behavioralRed||linked.originalHash!==linked.restoredHash||sha(linked.file)!==linked.restoredHash)throw new Error('Linked reverse-fault restoration failed');
const manifest=read(out+'/impact-analysis.json');const linkedTest='runner-v2/test/linked-output-spill-storage.test.ts';if(!manifest.tests.some(e=>e.path===linkedTest))manifest.tests.push({path:linkedTest,reasons:['causal Linux fixture contract correction']});
const replacements=new Set([...changedTests,linkedTest]);const files=manifest.tests.map(e=>({...e,sha256:sha(e.path),evidence:replacements.has(e.path)?'windows-linked-complete':e.path==='runner-v2/test/cli-capabilities-config.test.ts'?'cli-complete-recheck':manifest.groups.completeMcpShared.includes(e.path)?'windows-mcp-shared':manifest.groups.completeLsp.includes(e.path)?'windows-lsp-acceptance':'windows-affected-acceptance'}));
const importGraph=read(out+'/live-import-closure.json').imports;const crossTestImports=Object.entries(importGraph).flatMap(([p,edges])=>!changedTests.includes(p)?edges.filter(e=>changedTests.includes(e.target)).map(e=>({from:p,to:e.target})):[]);if(crossTestImports.length)throw new Error('Cannot reuse unaffected tests importing changed test fixtures');
const inputs=[...walk('runner-v2/src'),...walk('runner-v2/test'),...['package.json','package-lock.json','tsconfig.json','runner-v2/tsconfig.json','eslint.config.mjs','node_modules/typescript/package.json','node_modules/tsx/package.json','node_modules/eslint/package.json']].sort().map(p=>({path:p,sha256:sha(p)}));
const digest=crypto.createHash('sha256').update(JSON.stringify(inputs)).digest('hex');
const linuxFinalInputs=read(out+'/linux-shared-final/inputs-after.json');if(linuxFinalInputs.some(e=>sha(e.path)!==e.sha256))throw new Error('Final Linux inputs differ from live source');
function commandCounts(id){return fs.readFileSync(out+'/'+id+'/test.stdout.log','utf8').split(/^LINUX_COMMAND \d+ /m).slice(1).map(part=>Object.fromEntries([...part.matchAll(/^# (tests|pass|fail|cancelled|skipped) (\d+)$/gm)].map(m=>[m[1],Number(m[2])])));}
const linuxCounts=[...commandCounts('linux-lsp-shared-acceptance').slice(0,3),...commandCounts('linux-shared-final')];if(linuxCounts.some(c=>c.fail!==0||c.cancelled!==0))throw new Error('Accepted Linux command is not green');
const totals={windows:{files:files.length,tests:windows[0].counts.tests+windows[1].counts.tests+graph.counts.tests+2,passed:windows[0].counts.pass+windows[1].counts.pass+graph.counts.pass+1+2,failed:0,cancelled:0,skipped:1},linux:{tests:linuxCounts.reduce((n,c)=>n+c.tests,0),passed:linuxCounts.reduce((n,c)=>n+c.pass,0),failed:0,cancelled:0,skipped:linuxCounts.reduce((n,c)=>n+c.skipped,0)},distinctCausalFaults:26};
const result={verifiedAt:new Date().toISOString(),baseHead:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),task83:'VERIFIED',task84Eligible:true,task84Implemented:false,p6Complete:false,inputDigest:digest,totals,windows,statics,linux:{acceptedInitialCommands:linuxFirst.slice(0,3),finalCommands:linuxFinal,finalReceipt:linuxReceipt,unchangedPositiveFamilyWithUnrelatedTestFixtureDrift:linuxDrift},protected:{count:baseline.protectedFiles.length,drift:[],indexPreserved:true},resources:{hostRoots:resources.hostRootCount,absent:resources.absentHostRoots,retainedClosedEvidence:resources.retainedHostRoots.length,unresolved:0},validationReuse:'Complete files were executed across source-bound runs. Only three linked-spill test adapter compositions and two new helper/test files changed after the broad run; their four complete files were rerun. No other test imports those changed test files. The sole CLI readiness failure was superseded by an unchanged complete 18-test CLI run; no causal product fix is claimed for that transient observation. The original failing receipts are retained.',limitations:'Windows POSIX-only skip is covered by 44 real Linux POSIX checks; Linux Windows-only batch skip is covered natively. Historical failures/interruptions remain exclusions, never fabricated passes or release proofs.'};
fs.writeFileSync(out+'/accepted-inputs.json',JSON.stringify({inputDigest:digest,inputs},null,2),{flag:'wx'});fs.writeFileSync(out+'/affected-file-results.json',JSON.stringify({files,importClosureSha256:sha(out+'/live-import-closure.json'),crossTestImports},null,2),{flag:'wx'});fs.writeFileSync(out+'/acceptance.json',JSON.stringify(result,null,2),{flag:'wx'});
const review=read(out+'/requirements-review.json');for(const row of review.rows){for(const item of [...row.sources,...row.tests])item.sha256=sha(item.path);row.status='VERIFIED';}review.verifiedAt=result.verifiedAt;review.inputDigest=digest;review.acceptance='acceptance.json';fs.writeFileSync(out+'/requirements-review-final.json',JSON.stringify(review,null,2),{flag:'wx'});
fs.writeFileSync(out+'/protected-preservation.json',JSON.stringify({verifiedAt:result.verifiedAt,baselineSha256:sha(out+'/baseline.json'),count:baseline.protectedFiles.length,files:baseline.protectedFiles,unchanged:true,indexSha256:sha(out+'/index.txt')},null,2),{flag:'wx'});
console.log(JSON.stringify({totals,inputDigest:digest,resources:result.resources,protected:result.protected}));
