import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
const task='.superpowers/sdd/2026-09-11-p6-completion/task8-3-lsp',out=task+'/acceptance-final-20260913';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,'')),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const a=read(out+'/acceptance.json');if(a.task83!=='VERIFIED')throw new Error('Acceptance unavailable');
const audit=read(out+'/causal-evidence-audit.json'),materials=read(task+'/continue-20260912/material-results.json');
const replaced=new Set(['shutdown-omits-exit-budget','chunk-channel-bound','portable-input']);const pairs=[];
for(const p of audit.proofs.filter(p=>!replaced.has(p.id))){let red,green;if(materials.some(m=>m.id===p.id)){red=task+'/continue-20260912/fault-'+p.id+'-red';green=task+'/continue-20260912/fault-'+p.id+'-green';}else if(p.id==='language-phase-budget'){red=task+'/resume-20260912/lsp-language-budget-causal-red';green=task+'/resume-20260912/lsp-language-budget-causal-restored-green';}else if(['posix-anchor','descendant-fixture'].includes(p.id)){red=task+'/finish-20260913/'+p.id+'-reverse-red';green=task+'/finish-20260913/'+p.id+'-restored-green';}else{red=task+'/resume-20260912/rev-'+p.id+'-red';green=task+'/resume-20260912/rev-'+p.id+'-green';}pairs.push({id:p.id,target:p.target,test:p.test,red,green});}
for(const p of read(out+'/causal-refresh-results.json'))pairs.push({id:p.id,target:p.file,test:'runner-v2/test/'+p.test+'.test.ts',red:out+'/'+p.red.id,green:out+'/'+p.green.id,mutation:p});
pairs.push({id:'linked-test-storage-contract',target:'runner-v2/test/support/linked-output-spill-storage.ts',test:'runner-v2/test/linked-output-spill-storage.test.ts',red:out+'/linux-linked-regression-reverse-red',green:out+'/linux-shared-final',linux:true,mutation:read(out+'/linked-fixture-reverse-result.json')});
const records=[];
for(const p of pairs){const dir=out+'/causal-proof/'+p.id;fs.mkdirSync(dir,{recursive:true});const copies=[];for(const phase of ['red','green']){for(const name of ['terminal.json','inputs-before.json','inputs-after.json',p.linux?'test.stdout.log':'stdout.log',p.linux?'test.stderr.log':'stderr.log','wrapper.json','child.json']){const original=p[phase]+'/'+name;if(!fs.existsSync(original))continue;const dest=dir+'/'+phase+'-'+name;fs.copyFileSync(original,dest);copies.push({source:original,path:dest,sha256:sha(original)});}}const red=read(p.red+'/terminal.json'),green=read(p.green+'/terminal.json');if(red.exitCode!==1||green.exitCode!==0||!red.inputsUnchanged||!green.inputsUnchanged)throw new Error('Bad causal pair '+p.id);const record={...p,sourceFinalSha256:sha(p.target),testFinalSha256:sha(p.test),redReceipt:red,greenReceipt:green,copies};fs.writeFileSync(dir+'/proof.json',JSON.stringify(record,null,2));records.push(record);}
if(records.length!==26)throw new Error('Causal coverage count mismatch');fs.writeFileSync(out+'/causal-proof-index.json',JSON.stringify({faultCount:records.length,inputDigest:a.inputDigest,proofs:records.map(p=>({id:p.id,target:p.target,test:p.test,proof:'causal-proof/'+p.id+'/proof.json'})),note:'Proof logs and input manifests copied byte-for-byte from recorded runs; source provenance and hashes retained. Three older whole-file-source proofs were refreshed on final source. Linked test-adapter corrections changed no product source or existing assertions; affected complete test files were rerun.'},null,2),{flag:'wx'});
console.log(JSON.stringify({packagedCausalPairs:records.length,files:records.reduce((n,p)=>n+p.copies.length+1,0)}));
