import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
const task='.superpowers/sdd/2026-09-11-p6-completion/task8-3-lsp',out=task+'/acceptance-final-20260913',p6='.superpowers/sdd/2026-09-11-p6-completion';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8')),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),norm=p=>p.replaceAll('\\','/');
const git=(...args)=>execFileSync('git',args,{maxBuffer:64*1024*1024,stdio:['ignore','pipe','pipe']});
const a=read(out+'/acceptance.json'),inputs=read(out+'/accepted-inputs.json'),base=read(out+'/baseline.json');if(git('rev-parse','HEAD').toString().trim()!==a.baseHead||!fs.readFileSync(out+'/index.txt').equals(git('ls-files','--stage')))throw new Error('Git base or original index changed');
if(inputs.inputs.some(e=>sha(e.path)!==e.sha256)||base.protectedFiles.some(e=>!fs.existsSync(e.path)||sha(e.path)!==e.sha256))throw new Error('Source/protected bytes drifted');
const expectedSources=['cli.ts','code-intelligence-tools.ts','filesystem-tools.ts','language-intelligence.ts','language-provider-router.ts','language-server-executable.ts','lsp-client.ts','lsp-language-provider.ts','managed-process-supervisor.mjs','managed-process.ts','native-architect-runtime.ts','native-build-factory.ts','portable-process-supervisor.mjs','runner-internal-execution-context.ts','session-authority.ts','streaming-output-controller.ts','streaming-process-session-runtime.ts','streaming-request-operation.ts','subagent-tools.ts','windows-job-process-channel.ts','windows-job-process-host.ts','worker-runtime.ts','execution-host-lsp-transport.ts','language-agent-lifecycle.ts','lsp-transport.ts'].map(p=>'runner-v2/src/'+p);
const expectedTests=['bounded-output-spool.test.ts','evidence-continuation.test.ts','fixtures/lsp-server.mjs','language-provider-router.test.ts','lsp-client.test.ts','lsp-language-provider.test.ts','mcp-tools.test.ts','streaming-output-v2.test.ts','streaming-process-session-runtime.test.ts','language-agent-lifecycle.test.ts','language-environment.test.ts','language-executable-integrity.test.ts','language-invocation-propagation.test.ts','linked-output-spill-storage.test.ts','lsp-caller-audit.test.ts','lsp-descendant-fixture.test.ts','lsp-host-envelope.test.ts','lsp-initialize-rejection.test.ts','lsp-invocation-lifetime.test.ts','lsp-real-host.test.ts','lsp-router-authority.test.ts','lsp-server-control.test.ts','lsp-shared-client.test.ts','lsp-transport-authority.test.ts','lsp-transport-framing.test.ts','portable-supervisor-input.test.ts','posix-anchor-release-takeover.test.ts','streaming-language-operation.test.ts','support/linked-output-spill-storage.ts','support/lsp-language-fixture.ts','support/lsp-owned-fixture.ts','support/lsp-test-scope.ts','windows-job-output-replay.test.ts','windows-job-supervisor-input.test.ts'].map(p=>'runner-v2/test/'+p);
const runner=[...expectedSources,...expectedTests].sort(),dirty=git('status','--porcelain=v1','--untracked-files=all','--','runner-v2').toString().trimEnd().split(/\r?\n/).filter(Boolean).map(l=>l.slice(3)).sort();if(JSON.stringify(runner)!==JSON.stringify(dirty))throw new Error('Runner commit scope changed unexpectedly');
const docs=[task+'/report.md',task+'/plan.md',p6+'/plan.md',p6+'/task8-3-gate.json','.superpowers/sdd/2026-08-28-runner-v2-portable-execution-safety/task-8-brief.md'];
const top=['acceptance.json','accepted-inputs.json','affected-file-results.json','api-compatibility.json','baseline.json','index.txt','status.txt','impact-analysis.json','live-import-closure.json','requirements-review-final.json','protected-preservation.json','resource-accounting.json','git-inspection-state-observation.json','causal-proof-index.json','causal-evidence-audit.json','causal-refresh-results.json','linked-fixture-reverse-result.json','linked-fixture-red-inputs.json','linux-linked-fixture-diagnosis.json','progress.md','gate.mjs','linux-acceptance-gate.mjs','linux-selected-gate.mjs','refresh-causal.mjs','linked-reverse.mjs','acceptance-ledger.mjs','resource-audit.mjs','package-proof.mjs','prepare-commit.mjs','docker-start-handle.json'].map(p=>out+'/'+p);
const walk=p=>fs.readdirSync(p,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(p+'/'+e.name):[p+'/'+e.name]);
const evidence=[...top,...walk(out+'/causal-proof')];
const runIds=['windows-mcp-shared','windows-lsp-acceptance','windows-affected-acceptance','cli-complete-recheck','windows-linked-complete','typecheck-acceptance','eslint-acceptance','diff-check-acceptance','causal-current-controller','linked-fixture-reverse-controller','linux-controller','linux-shared-final-controller','linux-linked-regression-red-controller','linux-linked-regression-green-controller','linux-linked-regression-reverse-red-controller'];
for(const id of runIds){for(const e of fs.readdirSync(out+'/'+id,{withFileTypes:true}).filter(e=>e.isFile()))evidence.push(out+'/'+id+'/'+e.name);for(const suffix of ['.spec.json','-handle.json'])if(fs.existsSync(out+'/'+id+suffix))evidence.push(out+'/'+id+suffix);}
const linuxIds=['linux-lsp-shared-acceptance','linux-shared-final','linux-linked-regression-red','linux-linked-regression-green','linux-linked-regression-reverse-red'];
for(const id of linuxIds){for(const e of fs.readdirSync(out+'/'+id,{withFileTypes:true}).filter(e=>e.isFile()))evidence.push(out+'/'+id+'/'+e.name);for(const name of ['task83-linux-receipts.json','task83-runtime-inputs-before.json','task83-runtime-inputs-after.json','task83-runtime-terminal.json','task83-runtime-ownership.json'])if(fs.existsSync(out+'/'+id+'/tmp-evidence/'+name))evidence.push(out+'/'+id+'/tmp-evidence/'+name);if(fs.existsSync(out+'/'+id+'.linux.json'))evidence.push(out+'/'+id+'.linux.json');}
for(const id of ['current-chunk-limit','current-portable-callback','current-raw-launch-policy','current-shutdown-budget'])for(const phase of ['red','green'])evidence.push(out+'/'+id+'-'+phase+'.spec.json');
evidence.push(out+'/linked-fixture-change/manifest.json',out+'/linked-fixture-change/before/runner-v2/test/support/linked-output-spill-storage.ts');
const selected=[...new Set([...runner,...docs,...evidence])].sort();
for(const p of selected){if(!fs.existsSync(p)||!fs.statSync(p).isFile())throw new Error('Missing accepted file '+p);if(!p.startsWith('runner-v2/')&&!p.startsWith(out+'/')&&!docs.includes(p))throw new Error('Foreign selection '+p);if(/\.(sqlite|key|zip|dll|exe)$|\/bundle\//i.test(p))throw new Error('Protected/raw artifact selected '+p);}
const secretPatterns=[/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/,/\"token\"\s*:\s*\"[a-f0-9]{64}\"/i,/\"(?:api[_-]?key|access_token|refresh_token)\"\s*:\s*\"[A-Za-z0-9_\-]{32,}\"/i];
const findings=[];for(const p of selected){const text=fs.readFileSync(p,'utf8');for(let i=0;i<secretPatterns.length;i++)if(secretPatterns[i].test(text))findings.push({path:p,category:i});}
fs.writeFileSync(out+'/selection-secret-scan.json',JSON.stringify({at:new Date().toISOString(),fileCount:selected.length,findings,note:'Only pattern classifications and file paths are recorded; no matched credential values are printed.'},null,2),{flag:'wx'});if(findings.length)throw new Error('Potential authority material requires review; see selection-secret-scan.json');
const records=selected.map(p=>({path:p,sha256:sha(p),bytes:fs.statSync(p).size,kind:runner.includes(p)?'accepted-runner-change':docs.includes(p)?'task-gate-report':'source-bound-acceptance-evidence'}));
fs.writeFileSync(out+'/selection-manifest.json',JSON.stringify({at:new Date().toISOString(),baseHead:a.baseHead,inputDigest:a.inputDigest,runnerCount:runner.length,documentationCount:docs.length,evidenceCount:evidence.length,files:records},null,2),{flag:'wx'});
selected.push(out+'/selection-manifest.json',out+'/selection-secret-scan.json');selected.sort();fs.writeFileSync(out+'/selected-files.nul',Buffer.from(selected.join('\0')+'\0'));fs.writeFileSync(out+'/selected-files.txt',selected.join('\n')+'\n');
console.log(JSON.stringify({selectedFiles:selected.length,runnerFiles:runner.length,docs:docs.length,bytes:records.reduce((n,r)=>n+r.bytes,0),scanFindings:findings.length,indexStillPreserved:fs.readFileSync(out+'/index.txt').equals(git('ls-files','--stage'))}));
