import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';import {pathToFileURL} from 'node:url';
const out='.superpowers/sdd/2026-09-11-p6-completion/task8-3-lsp/acceptance-final-20260913';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,'')),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const normalized=p=>path.normalize(p).toLowerCase();
const runs=fs.readdirSync(out,{withFileTypes:true}).filter(e=>e.isDirectory()&&fs.existsSync(out+'/'+e.name+'/terminal.json')).map(e=>({id:e.name,receipt:read(out+'/'+e.name+'/terminal.json')}));
const processes=JSON.parse(execFileSync('powershell.exe',['-NoProfile','-Command','Get-CimInstance Win32_Process | Select-Object ProcessId,ParentProcessId,CreationDate,Name,CommandLine | ConvertTo-Json -Depth 3 -Compress'],{encoding:'utf8',maxBuffer:16*1024*1024}));
const roots=new Map();
for(const run of runs){const f=out+'/'+run.id+'/roots.json';if(!fs.existsSync(f))continue;const r=read(f);for(const entry of r.roots??[]){const n=normalized(entry.path);const item=roots.get(n)??{path:path.normalize(entry.path),runs:[]};item.runs.push(run.id);roots.set(n,item);}}
const hostRoots=[...roots.values()].map(r=>({...r,exists:fs.existsSync(r.path),matchingProcesses:processes.filter(p=>p.CommandLine&&normalized(p.CommandLine).includes(normalized(r.path))).map(p=>({pid:p.ProcessId,parentPid:p.ParentProcessId,start:p.CreationDate,name:p.Name}))}));
const log=fs.readFileSync(out+'/windows-affected-acceptance/stdout.log','utf8');
for(const r of hostRoots){if(!r.exists){r.classification='owner-verified fixture teardown followed by observed absence';continue;}if(path.basename(r.path).startsWith('c2r9-')){r.classification='deliberately retained closed synthetic DB/artifact fixture; no native process created';r.source='runner-v2/test/streaming-precheckpoint-recovery.test.ts';r.ownerCloseDiagnosticPresent=log.includes(r.path.replaceAll('\\','\\\\'));}else if(path.basename(r.path).startsWith('p683-shutdown-budget-'))r.classification='closed synthetic expected reverse-fault evidence; no native process created';else if(path.basename(r.path)==='aiboard-git-inspection-44myvG')r.classification='retained unsuccessful Git inspection evidence; exact authenticated empty-state audit below';else r.classification='UNRESOLVED';}
const {openSqliteDurableProcessKernel}=await import(pathToFileURL(path.resolve('runner-v2/src/durable-process-store.ts')).href);
const gitRoot='C:/Users/b_a_s/AppData/Local/Temp/aiboard-git-inspection-44myvG',key=fs.readFileSync(gitRoot+'/runtime/subprocess-runtime.key');
const kernel=openSqliteDurableProcessKernel(gitRoot+'/runtime/subprocess-runtime.sqlite',key,{readOnly:true});let records;
try{records=kernel.store.listRowIds().map(id=>{const r=kernel.store.readByInvocation(id);return {id,state:r.state,backendBound:Boolean(r.backendBinding),output:r.output};});}finally{kernel.store.close();key.fill(0);}
const gitStreaming=read(out+'/git-inspection-state-observation.json');
const containers=[];
for(const run of runs){const f=out+'/'+run.id+'/owned-container.json';if(!fs.existsSync(f))continue;const owned=read(f);let live,absent=false;try{const data=JSON.parse(execFileSync('docker',['inspect',owned.containerId],{encoding:'utf8',stdio:['ignore','pipe','pipe']}))[0];if(data.Config.Labels['com.aiboard.task83']!==owned.label)throw new Error('Exact container label mismatch');live={status:data.State.Status,running:data.State.Running,pid:data.State.Pid,exitCode:data.State.ExitCode,oom:data.State.OOMKilled};}catch(e){if(/No such object|No such container/i.test(String(e.stderr)))absent=true;else throw e;}containers.push({run:run.id,...owned,live,absent,classification:absent?'verified exact-owner removal':run.receipt.exitCode===1&&live.status==='exited'&&!live.running&&!live.oom?'failed or intentional RED evidence container retained, no running workload':'UNRESOLVED'});}
const relevantWrappers=processes.filter(p=>p.Name==='node.exe'&&p.CommandLine?.includes(path.resolve(out))&&/gate\.mjs|selected-gate|refresh-causal|linked-reverse/.test(p.CommandLine)).map(p=>({pid:p.ProcessId,start:p.CreationDate,name:p.Name}));
const unresolved=[...hostRoots.filter(r=>r.classification==='UNRESOLVED'||r.matchingProcesses.length>0),...containers.filter(c=>c.classification==='UNRESOLVED'),...records.filter(r=>r.state!=='cleaned'),...relevantWrappers];
const result={at:new Date().toISOString(),hostRootCount:hostRoots.length,absentHostRoots:hostRoots.filter(r=>!r.exists).length,retainedHostRoots:hostRoots.filter(r=>r.exists),allHostRoots:hostRoots,containers,gitInspection:{streaming:gitStreaming,subprocessRecords:records},activeTaskWrappers:relevantWrappers,unresolved,syntheticFixtureSourceSha256:sha('runner-v2/test/streaming-precheckpoint-recovery.test.ts'),note:'No historical roots, failed evidence or SQLite rows modified. Expected synthetic unverified records are not native resources and are not relabeled released. Root absence complements fixture owner assertions; it never substitutes for them. Failed containers remain preserved after exact-ID/label exited-state verification.'};
fs.writeFileSync(out+'/resource-accounting.json',JSON.stringify(result,null,2),{flag:'wx'});console.log(JSON.stringify({hostRootCount:result.hostRootCount,absentHostRoots:result.absentHostRoots,retained:result.retainedHostRoots.map(r=>({path:r.path,classification:r.classification,matchingProcesses:r.matchingProcesses})),containers:containers.map(c=>({id:c.containerId,classification:c.classification})),gitRecords:records,unresolvedCount:unresolved.length}));
if(unresolved.length)process.exitCode=1;
