// build-runner.mjs — bundle the multi-file dev runner into the single-file
// public/runner.mjs that the app serves for download. Inlines runner-lib.mjs
// (merging node: imports) and the control-panel HTML, so the runner still
// distributes as ONE zero-dependency file. Replaces the old copy-runner copy.
//
// Run: node scripts/build-runner.mjs   (invoked by predev/prebuild)

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, "..");
const SRC = path.join(here, "runner.mjs");
const LIB = path.join(here, "runner-lib.mjs");
const PANEL = path.join(here, "runner-panel.html");
const OUT = path.join(repo, "public", "runner.mjs");

const SINGLE_IMPORT = /^import\s+(?:([A-Za-z_$][\w$]*)\s*,?\s*)?(?:\{([^}]*)\})?\s*from\s*["'](node:[^"']+)["'];?\s*$/;

/** Split source into a body (imports removed) and a list of parsed node: imports. */
function extractNodeImports(src) {
  const kept = [];
  const imports = [];
  for (const line of src.split(/\r?\n/)) {
    const m = SINGLE_IMPORT.exec(line.trim());
    if (m) {
      imports.push({
        def: m[1] || null,
        names: m[2] ? m[2].split(",").map((s) => s.trim()).filter(Boolean) : [],
        mod: m[3],
      });
    } else {
      kept.push(line);
    }
  }
  return { body: kept.join("\n"), imports };
}

/** Merge node: imports across files: one statement per module, named bindings unioned. */
function mergeImports(imports) {
  const byMod = new Map();
  for (const imp of imports) {
    if (!byMod.has(imp.mod)) byMod.set(imp.mod, { def: null, names: new Set() });
    const g = byMod.get(imp.mod);
    if (imp.def) g.def = imp.def;
    for (const n of imp.names) g.names.add(n);
  }
  const out = [];
  for (const [mod, g] of byMod) {
    const parts = [];
    if (g.def) parts.push(g.def);
    if (g.names.size) parts.push(`{ ${[...g.names].join(", ")} }`);
    out.push(`import ${parts.join(", ")} from "${mod}";`);
  }
  return out.join("\n");
}

// Lib: strip `export ` so its declarations become plain top-level bindings.
const libSrc = fs
  .readFileSync(LIB, "utf8")
  .replace(/^#![^\n]*\n/, "")
  .replace(/^export\s+/gm, "");
const lib = extractNodeImports(libSrc);

// Runner: a leading shebang is only valid as line 1, so hoist it to the very
// top of the bundle; drop the local runner-lib import (it gets inlined).
let runnerSrc = fs.readFileSync(SRC, "utf8");
const shebang = (runnerSrc.match(/^#![^\n]*\n/) || [""])[0];
runnerSrc = runnerSrc.replace(/^#![^\n]*\n/, "");
runnerSrc = runnerSrc.replace(/import\s*\{[^}]*\}\s*from\s*["']\.\/runner-lib\.mjs["'];?/s, "");
const runner = extractNodeImports(runnerSrc);

// Panel: inline at the marker (JSON.stringify handles all escaping).
const panel = fs.readFileSync(PANEL, "utf8");
let runnerBody = runner.body.replace('"__RUNNER_PANEL_HTML__"', JSON.stringify(panel));
if (runnerBody.includes("__RUNNER_PANEL_HTML__")) {
  throw new Error("Panel marker not found/replaced in runner.mjs");
}
if (runnerBody.includes("runner-lib.mjs")) {
  throw new Error("Leftover runner-lib import in bundled output");
}

const mergedImports = mergeImports([...runner.imports, ...lib.imports]);
const banner =
  "// AUTO-GENERATED by scripts/build-runner.mjs — do not edit.\n" +
  "// Sources: scripts/runner.mjs + runner-lib.mjs + runner-panel.html\n";
const output = `${shebang}${banner}${mergedImports}\n\n// ── inlined helpers ──\n${lib.body}\n\n// ── runner ──\n${runnerBody}\n`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, output);

// Release manifest: the app reads it to show the download version + an "update
// available" nudge; the runner's self-update verifies the SHA-256 (and, later,
// an Ed25519 signature) against it. The hash is over the exact bytes written.
const version = Number((output.match(/const VERSION = (\d+)/) || [])[1] || 0);
const sha256 = createHash("sha256").update(output).digest("hex");
const manifest = { version, sha256, url: "/runner.mjs" };
fs.writeFileSync(path.join(repo, "public", "runner-manifest.json"), JSON.stringify(manifest, null, 2) + "\n");
console.log(
  `Built ${path.relative(repo, OUT)} v${version} — ${(output.length / 1024).toFixed(1)} kB (panel ${(panel.length / 1024).toFixed(1)} kB); manifest sha256 ${sha256.slice(0, 12)}…`
);
