/* Regenerates lib/benchmark/gameiq/saturation.ts from exported run files.
 *
 * Usage:
 *   npx tsx scripts/generate-gameiq-saturation.mts <run1.json> <run2.json> ... > lib/benchmark/gameiq/saturation.ts
 *
 * For each run file we read runs[0].modelIds[0] (the model id) and its recorded
 * model-call traces, then for every pack in listGameIqScenarioPacks() we replay
 * the pack's traces through the REAL v0.3 scorer (resolvePackTraceReplay +
 * runGameIqScenarios) — the SAME uniform path used by the replay/recovery CLIs,
 * so completed and recovered/partial runs are treated identically. Each scored
 * (not `unscored`) caseResult contributes a per-(scenario, model) `correct`
 * verdict.
 *
 * A scenario is SATURATED when at least GAMEIQ_SATURATION_MIN_MODELS distinct
 * models have a verdict for it AND every one of those verdicts is correct.
 *
 * The emitted module is DETERMINISTIC and byte-stable: ids are sorted and no
 * wall-clock timestamp is written, so re-running the generator over the same
 * inputs produces a byte-identical file (clean diff).
 */
import { readFileSync } from "node:fs";
import {
  GAMEIQ_CORRECT_QUALITY_BAR,
  GAMEIQ_SCORING_VERSION,
  listGameIqScenarioPacks,
  resolvePackTraceReplay,
  runGameIqScenarios,
  type PackTraceRow,
} from "../lib/benchmark/gameiq";

const GAMEIQ_SATURATION_MIN_MODELS = 3;

interface RunSummary {
  runId: string;
  modelId: string;
  scenarioVerdicts: number;
  packsContributing: number;
}

async function main(): Promise<void> {
  const files = process.argv.slice(2);
  if (files.length === 0) {
    console.error(
      "Usage: npx tsx scripts/generate-gameiq-saturation.mts <run1.json> <run2.json> ... > lib/benchmark/gameiq/saturation.ts"
    );
    process.exit(2);
  }

  const packs = listGameIqScenarioPacks();
  // scenarioId -> modelId -> correct
  const verdicts = new Map<string, Map<string, boolean>>();
  const runSummaries: RunSummary[] = [];

  for (const file of files) {
    const bundle = JSON.parse(readFileSync(file, "utf8"));
    const runId: string = bundle.runs?.[0]?.id ?? file;
    const modelId: string | undefined = bundle.runs?.[0]?.modelIds?.[0];
    if (!modelId) {
      throw new Error(`Run file ${file} has no runs[0].modelIds[0].`);
    }
    const traces: PackTraceRow[] = bundle.traces ?? [];

    let scenarioVerdicts = 0;
    let packsContributing = 0;
    for (const pack of packs) {
      const packTraces = traces.filter((trace) => trace.caseId === pack.id);
      if (packTraces.length === 0) continue;
      const { replayScenarios, actions } = resolvePackTraceReplay(
        pack,
        packTraces
      );
      if (replayScenarios.length === 0) continue;
      let cursor = 0;
      const result = await runGameIqScenarios({
        runId: "saturation-replay",
        modelId,
        teamCompositionId: "saturation-replay",
        caseId: pack.id,
        scenarios: replayScenarios,
        moveProvider: () => ({ action: actions[cursor++] }),
      });
      let packContributed = false;
      for (const caseResult of result.caseResults) {
        if (caseResult.unscored) continue;
        packContributed = true;
        scenarioVerdicts++;
        let modelMap = verdicts.get(caseResult.scenarioId);
        if (!modelMap) {
          modelMap = new Map();
          verdicts.set(caseResult.scenarioId, modelMap);
        }
        modelMap.set(modelId, caseResult.correct);
      }
      if (packContributed) packsContributing++;
    }

    runSummaries.push({ runId, modelId, scenarioVerdicts, packsContributing });
  }

  const saturatedIds: string[] = [];
  for (const [scenarioId, modelMap] of verdicts) {
    if (modelMap.size < GAMEIQ_SATURATION_MIN_MODELS) continue;
    if ([...modelMap.values()].every((correct) => correct === true)) {
      saturatedIds.push(scenarioId);
    }
  }
  saturatedIds.sort();

  const runLines = runSummaries.map(
    (summary) =>
      `//   ${summary.modelId} (${summary.runId}) — ${summary.scenarioVerdicts} scenarios across ${summary.packsContributing} packs`
  );
  const idLines = saturatedIds.map((id) => `  ${JSON.stringify(id)},`);

  const out = [
    "// AUTO-GENERATED by scripts/generate-gameiq-saturation.mts — DO NOT hand-edit.",
    "// Regenerate: npx tsx scripts/generate-gameiq-saturation.mts <run files...> > lib/benchmark/gameiq/saturation.ts",
    "// Source runs (model — packs contributing verdicts):",
    ...runLines,
    `// Generated from ${runSummaries.length} runs; a scenario is listed when >= ${GAMEIQ_SATURATION_MIN_MODELS} models attempted it and ALL solved it.`,
    `// Definition: correct = actionQuality >= GAMEIQ_CORRECT_QUALITY_BAR (${GAMEIQ_CORRECT_QUALITY_BAR}) under scoring ${GAMEIQ_SCORING_VERSION}.`,
    `export const GAMEIQ_SATURATION_MIN_MODELS = ${GAMEIQ_SATURATION_MIN_MODELS};`,
    "export const GAMEIQ_SATURATED_SCENARIO_IDS: ReadonlySet<string> = new Set([",
    ...idLines,
    "]);",
    "",
  ].join("\n");

  process.stdout.write(out);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.stack ?? error.message : String(error));
  process.exit(1);
});
