import {createReplayInput} from '../benchmarks/recoverable-job-service/private/replay.mjs';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {validateResponse} from '../benchmarks/recoverable-job-service/private/response-schema.mjs';
import * as wire from '../benchmarks/recoverable-job-service/private/wire-schema.mjs';
import {effectiveProvenance,schedulePlan} from '../benchmarks/recoverable-job-service/private/provenance.mjs';
import {variants} from '../benchmarks/recoverable-job-service/private/variants.mjs';
import {evaluateBounded} from '../benchmarks/recoverable-job-service/private/runtime.mjs';
import {comparisonIdentity} from '../benchmarks/recoverable-job-service/private/qualification-provenance.mjs';
import {controls} from '../benchmarks/recoverable-job-service/private/controls.mjs';
import {materialControl} from '../benchmarks/recoverable-job-service/private/qualification-map.mjs';

const tests:Record<string,()=>void|Promise<void>>={};
const id=(n:number)=>n.toString(16).padStart(32,'0');
const receipt=(n:number)=>({id:id(n),operationId:id(n+100),effect:'store.commit',resourceId:id(201),ownerId:id(202),epoch:1,appliedAt:1,payload:{revision:n},token:'a'.repeat(64)});
const nestedReceipt=(depth:number):any=>depth===0?receipt(1):{...receipt(depth+1),effect:'driver.detach',payload:{reader:nestedReceipt(depth-1)}};
function capsule(field:string,receipts:any[]){
 const value:any={format:3,scopeId:id(301),batchId:id(302),jobId:id(303),setupId:id(304),ownerId:id(202),epoch:1,revision:1,checkpointEverCreated:false,seal:'shape-only',extensions:{},receipts:[],checkpoint:null};
 if(field==='receipts')value.receipts=receipts;
 else{value.checkpointEverCreated=true;value.checkpoint={generation:id(305),createdAt:1,accepted:[],consumed:[],retirement:[],authority:{ownerId:id(202),epoch:1},retiredThrough:{stdout:{seq:0,offset:0,receipt:null},stderr:{seq:0,offset:0,receipt:null}}};value.checkpoint[field]=receipts;}
 return {kind:'ok',value};
}
for(const field of ['receipts','consumed','retirement']){
 tests['N1-long-'+field]=()=>{for(const count of [9,10,12])assert.doesNotThrow(()=>validateResponse('exportCapsule',capsule(field,Array.from({length:count},(_,i)=>receipt(i+1)))),'schema-valid '+field+' length '+count);const members=Array.from({length:12},(_,i)=>receipt(i+1));members[10]=nestedReceipt(8);assert.doesNotThrow(()=>validateResponse('exportCapsule',capsule(field,members)),'array position does not add recursive depth');};
 tests['N1-malformed-'+field]=()=>{const members=Array.from({length:12},(_,i)=>receipt(i+1));members[10]={...members[10],payload:null} as any;assert.throws(()=>validateResponse('exportCapsule',capsule(field,members)),/Invalid public response/);};
}
tests['N1-nested-depth']=()=>{assert.equal(wire.receipt(nestedReceipt(8)),true,'eight nested receipt edges are legal');assert.equal(wire.receipt(nestedReceipt(9)),false,'nine nested receipt edges exceed the real depth bound');};
tests['I6-singleton-production-schedules']=()=>{const full=schedulePlan('qualification-v1');assert.equal(full.length,302);assert.deepEqual(full.find((v:any)=>v.id==='A02/primary').schedule,{partition:2606,delay:1});for(const variant of variants)assert.deepEqual(schedulePlan('qualification-v1',[variant])[0],full.find((v:any)=>v.id===variant.id),variant.id+' retains the full production schedule');};
tests['I6-mixed-selected-schedules']=()=>{const selected=[variants[226],variants[1],variants[70]],full=schedulePlan('qualification-v1');for(const seed of ['qualification-v1','different-seed']){const all=schedulePlan(seed);assert.deepEqual(schedulePlan(seed,selected),selected.map((v:any)=>all.find((r:any)=>r.id===v.id)));}assert.notDeepEqual(full,schedulePlan('different-seed'));};
tests['I6-run-identity-remains-selected']=()=>{const full=effectiveProvenance(),selected=effectiveProvenance({families:['A02'],variantIds:['A02/primary']});assert.equal(full.mode,'production');assert.equal(selected.mode,'development');assert.notEqual(full.configurationHash,selected.configurationHash);assert.notEqual(full.scheduleHash,selected.scheduleHash);assert.throws(()=>effectiveProvenance({mode:'production',families:['A02'],variantIds:['A02/primary']}),/Production scoring options are frozen/);};
tests['I6-bounded-execution-inputs']=async()=>{const reference=await readFile(new URL('../benchmarks/recoverable-job-service/private/reference.js',import.meta.url),'utf8'),observations:any[]=[];const result=await evaluateBounded(reference,{families:['A02'],variantIds:['A02/primary'],onVariantStart:(v:any)=>observations.push(v)});assert.equal(result.status,'valid');assert.equal(result.families[0].passed,true);assert.equal(result.resolved,false);assert.equal(observations.length,1,'bounded qualification observes actual variant execution inputs');const event=observations[0];assert.equal(event.variantId,'A02/primary');assert.deepEqual(event.execution.schedule,{partition:2606,delay:1});assert.equal(event.execution.brokerSeed,'rjs-suite-1/A02/qualification-v1');assert.equal(event.execution.limits.wallMs,60000);assert.equal(event.execution.limits.operations,100000);assert.equal(event.execution.limits.promiseJobs,1000000);assert.equal(event.execution.largeCount,1025);assert.equal(event.runtime.entryPoint,'evaluateBounded');assert.equal(event.runtime.node,'24.18.0');assert.equal(event.runtime.familyWallMs,60000);assert.equal(event.runtime.totalWallMs,600000);assert.equal(event.runtime.externalVariantAllowanceMs,250);
 const identity=comparisonIdentity(result,event);assert.match(identity.comparisonHash,/^[a-f0-9]{64}$/);assert(identity.canonicalEnvironment.includes('"partition":2606'));
 for(const change of [(e:any)=>e.execution.schedule.partition++,(e:any)=>e.execution.variant.args.extra=true,(e:any)=>e.execution.seed='other',(e:any)=>e.execution.limits.wallMs=2000,(e:any)=>e.execution.limits.operations++,(e:any)=>e.runtime.totalWallMs++,(e:any)=>e.runtime.entryPoint='evaluate',(e:any)=>e.runtime.externalVariantAllowanceMs++]){const wrong=structuredClone(event);change(wrong);assert.throws(()=>comparisonIdentity(result,wrong),'mismatched actual execution evidence is rejected');}
 const wrongRun=structuredClone(result);wrongRun.provenance.configurationHash='0'.repeat(64);assert.throws(()=>comparisonIdentity(wrongRun,event),'forged whole-run identity is rejected');const changedSuite=structuredClone(result);changedSuite.suiteHash='0'.repeat(64);assert.notEqual(comparisonIdentity(changedSuite,event).comparisonHash,identity.comparisonHash,'different evaluator identity cannot compare equal');
};

for(const [variantId,assertion]of [['A08/primary','poll must progress'],['A08/nested-consumer-progress','poll must progress'],['D09/primary','ACK-gated output drained before destructive stop'],['B14/primary','snapshot reaches every owned setup beyond pages']])tests['I6-causal-'+variantId]=async()=>{
 const reference=await readFile(new URL('../benchmarks/recoverable-job-service/private/reference.js',import.meta.url),'utf8'),variant=variants.find((v:any)=>v.id===variantId),control=materialControl(variant),negativeInputs:any[]=[],restoredInputs:any[]=[];
 const options={replayInput:createReplayInput(),mode:'development',families:[variant.family],variantIds:[variantId],seed:'qualification-v1',wallMs:60000,totalWallMs:600000,largeCount:1025};
 const negative=await evaluateBounded(controls[control].mutate(reference),{...options,onVariantStart:(v:any)=>negativeInputs.push(v)}),restored=await evaluateBounded(reference,{...options,onVariantStart:(v:any)=>restoredInputs.push(v)});
 assert.equal(negative.status,'valid');assert.equal(restored.status,'valid');assert.equal(negativeInputs.length,1);assert.equal(restoredInputs.length,1);assert.deepEqual(negative.provenance,restored.provenance);assert.deepEqual(comparisonIdentity(negative,negativeInputs[0]),comparisonIdentity(restored,restoredInputs[0]));
 const row=negative.families[0].variants[0];console.log(variantId+' actual causal failure: '+row.reason);assert.equal(row.passed,false);assert(!/Invalid public response|candidate wall timeout|watchdog/i.test(row.reason));assert(row.assertions.some((a:any)=>!a.passed&&a.label.startsWith(assertion))||variantId==='B14/primary'&&row.reason.startsWith('closeBatch must refuse')&&row.assertions.some((a:any)=>!a.passed&&a.label==='closeBatch must refuse')&&row.safetyFailures.some((f:any)=>f.code==='close-owned-records'),'the intended existing public assertion fails');assert.equal(restored.families[0].passed,true);assert.equal(restored.families[0].safetyChecked,true);assert.equal(restored.safetyFailures.length,0);
};
const selected=Object.entries(tests).filter(([name])=>!process.argv[2]||name.startsWith(process.argv[2]));assert(selected.length>0);let failures=0;for(const [name,test] of selected){try{await test();console.log('PASS '+name);}catch(e){failures++;console.error('FAIL '+name+': '+(e as Error).message);}}console.log(selected.length+' selected, '+failures+' failed');if(failures)process.exitCode=1;
