import assert from "node:assert/strict";

import { mapNativeBuildUsageModels } from "../lib/client/native-model-usage";
import type { NativeBuildUsageProjection } from "../lib/client/runner-v2";

function projection(
  effective: Partial<NativeBuildUsageProjection["effective"]>,
  models?: NativeBuildUsageProjection["models"]
): NativeBuildUsageProjection {
  return {
    scopeId: "run_1",
    reservations: {},
    activeSegments: {},
    effective: {
      modelCalls: 0,
      toolCalls: 0,
      inputTokens: 0,
      cachedInputTokens: 0,
      cacheWriteInputTokens: 0,
      outputTokens: 0,
      estimatedCostMicros: 0,
      activeMs: 0,
      artifactBytes: 0,
      ...effective,
    },
    ...(models === undefined ? {} : { models }),
    lastSequence: 1,
  };
}

const realRows = mapNativeBuildUsageModels(projection(
  {
    modelCalls: 99,
    inputTokens: 999,
    cachedInputTokens: 111,
    cacheWriteInputTokens: 222,
    outputTokens: 333,
  },
  [
    {
      runtimeId: "runtime-b",
      providerId: "provider-b",
      modelId: "model-b",
      roles: ["worker", "subagent"],
      status: "cooldown",
      calls: 2,
      inputTokens: 120,
      cachedInputTokens: 30,
      cacheWriteInputTokens: 20,
      outputTokens: 40,
      totalTokens: 160,
      estimatedCostMicros: null,
      costBasis: "account_not_metered",
      usageQuality: "mixed",
      lastUsedAt: "2026-07-12T10:11:12.000Z",
    },
    {
      runtimeId: "runtime-a",
      providerId: "provider-a",
      modelId: "model-a",
      roles: ["architect"],
      status: "unused",
      calls: 0,
      inputTokens: 0,
      cachedInputTokens: 0,
      cacheWriteInputTokens: 0,
      outputTokens: 0,
      totalTokens: 0,
      estimatedCostMicros: 0,
      costBasis: "api_estimate",
      usageQuality: "none",
      lastUsedAt: null,
    },
  ]
));

assert.deepEqual(realRows, [
  {
    runtimeId: "runtime-b",
    modelId: "model-b",
    modelName: "model-b",
    providerId: "provider-b",
    roles: ["worker", "subagent"],
    status: "cooldown",
    calls: 2,
    inputTokens: 120,
    cachedInputTokens: 30,
    cacheWriteInputTokens: 20,
    outputTokens: 40,
    totalTokens: 160,
    estimatedUsd: null,
    priced: false,
    usageQuality: "mixed",
    costBasis: "account_not_metered",
    lastUsedAt: "2026-07-12T10:11:12.000Z",
    usageOrigin: "native",
  },
  {
    runtimeId: "runtime-a",
    modelId: "model-a",
    modelName: "model-a",
    providerId: "provider-a",
    roles: ["architect"],
    status: "unused",
    calls: 0,
    inputTokens: 0,
    cachedInputTokens: 0,
    cacheWriteInputTokens: 0,
    outputTokens: 0,
    totalTokens: 0,
    estimatedUsd: 0,
    priced: true,
    usageQuality: "none",
    costBasis: "api_estimate",
    lastUsedAt: null,
    usageOrigin: "native",
  },
]);

const previewRows = mapNativeBuildUsageModels(projection(
  {
    modelCalls: 5,
    inputTokens: 11,
    cachedInputTokens: 5,
    cacheWriteInputTokens: 2,
    outputTokens: 7,
    estimatedCostMicros: 500_000,
  },
  [
    {
      runtimeId: "runtime-z",
      providerId: "provider-z",
      modelId: "model-z",
      roles: ["architect", "worker"],
      status: "healthy",
      calls: 0,
      inputTokens: 0,
      cachedInputTokens: 0,
      cacheWriteInputTokens: 0,
      outputTokens: 0,
      totalTokens: 0,
      estimatedCostMicros: 0,
      costBasis: "api_estimate",
      usageQuality: "none",
      lastUsedAt: null,
    },
    {
      runtimeId: "runtime-a",
      providerId: "provider-a",
      modelId: "model-a",
      roles: ["subagent"],
      status: "unavailable",
      calls: 0,
      inputTokens: 0,
      cachedInputTokens: 0,
      cacheWriteInputTokens: 0,
      outputTokens: 0,
      totalTokens: 0,
      estimatedCostMicros: null,
      costBasis: "account_not_metered",
      usageQuality: "none",
      lastUsedAt: null,
    },
    {
      runtimeId: "runtime-b",
      providerId: "provider-b",
      modelId: "model-b",
      roles: ["architect"],
      status: "cooldown",
      calls: 0,
      inputTokens: 0,
      cachedInputTokens: 0,
      cacheWriteInputTokens: 0,
      outputTokens: 0,
      totalTokens: 0,
      estimatedCostMicros: null,
      costBasis: "unknown",
      usageQuality: "none",
      lastUsedAt: null,
    },
  ]
));

assert.deepEqual(
  previewRows.map((row) => ({
    runtimeId: row.runtimeId,
    roles: row.roles,
    status: row.status,
    calls: row.calls,
    inputTokens: row.inputTokens,
    cachedInputTokens: row.cachedInputTokens,
    cacheWriteInputTokens: row.cacheWriteInputTokens,
    outputTokens: row.outputTokens,
    totalTokens: row.totalTokens,
    estimatedUsd: row.estimatedUsd,
    priced: row.priced,
    usageQuality: row.usageQuality,
    costBasis: row.costBasis,
    lastUsedAt: row.lastUsedAt,
    usageOrigin: row.usageOrigin,
  })),
  [
    {
      runtimeId: "runtime-a",
      roles: ["subagent"],
      status: "unavailable",
      calls: 1,
      inputTokens: 2,
      cachedInputTokens: 1,
      cacheWriteInputTokens: 0,
      outputTokens: 1,
      totalTokens: 3,
      estimatedUsd: null,
      priced: false,
      usageQuality: "estimated",
      costBasis: "account_not_metered",
      lastUsedAt: null,
      usageOrigin: "legacy_preview",
    },
    {
      runtimeId: "runtime-b",
      roles: ["architect"],
      status: "cooldown",
      calls: 2,
      inputTokens: 4,
      cachedInputTokens: 2,
      cacheWriteInputTokens: 1,
      outputTokens: 2,
      totalTokens: 6,
      estimatedUsd: null,
      priced: false,
      usageQuality: "estimated",
      costBasis: "unknown",
      lastUsedAt: null,
      usageOrigin: "legacy_preview",
    },
    {
      runtimeId: "runtime-z",
      roles: ["architect", "worker"],
      status: "healthy",
      calls: 2,
      inputTokens: 5,
      cachedInputTokens: 2,
      cacheWriteInputTokens: 1,
      outputTokens: 4,
      totalTokens: 9,
      estimatedUsd: null,
      priced: false,
      usageQuality: "estimated",
      costBasis: "api_estimate",
      lastUsedAt: null,
      usageOrigin: "legacy_preview",
    },
  ]
);

for (const key of [
  "calls",
  "inputTokens",
  "cachedInputTokens",
  "cacheWriteInputTokens",
  "outputTokens",
] as const) {
  assert.equal(
    previewRows.reduce((sum, row) => sum + row[key], 0),
    projection({
      modelCalls: 5,
      inputTokens: 11,
      cachedInputTokens: 5,
      cacheWriteInputTokens: 2,
      outputTokens: 7,
    }).effective[key === "calls" ? "modelCalls" : key]
  );
}
assert.equal(previewRows.reduce((sum, row) => sum + row.totalTokens, 0), 18);

const compatibilityRows = mapNativeBuildUsageModels(projection({
  modelCalls: 3,
  inputTokens: 10,
  cachedInputTokens: 4,
  cacheWriteInputTokens: 1,
  outputTokens: 2,
  estimatedCostMicros: 123_000,
}));
assert.deepEqual(compatibilityRows, [{
  modelId: "runner-v2:aggregate",
  modelName: "Runner V2 models (legacy aggregate)",
  providerId: "runner-v2",
  roles: [],
  calls: 3,
  inputTokens: 10,
  cachedInputTokens: 4,
  cacheWriteInputTokens: 1,
  outputTokens: 2,
  totalTokens: 12,
  estimatedUsd: null,
  priced: false,
  usageQuality: "estimated",
  costBasis: "unknown",
  lastUsedAt: null,
  usageOrigin: "legacy_aggregate",
}]);

console.log("PASS native Build model usage mapping");
