import assert from 'node:assert/strict';
import {Broker,canonical} from '../benchmarks/recoverable-job-service/private/broker.mjs';
const b=new Broker('source-adapter');
assert.equal(typeof b.sourcePrelude,'function','public source construction primitive exists');
const input=b.sourcePrelude({streams:{stdout:[[11,12,13],[21,22]],stderr:[[7,8]]}});
const jobId=b.id(),fence={grant:b.grant,deadline:1000};
for(const resource of ['isolation','process','channel','workload'])await b.call('driver.acquire',{jobId,resource,operationId:b.id(),fence});
const j=b.getJob(jobId);
const early=await b.call('driver.attach',{jobId,operationId:b.id(),fence});
assert.equal(early.value.payload.source.streams.stdout.advanced.offset,0);
await b.call('driver.start',{jobId,workloadId:input.workloadId,workload:j.workload,witness:j.witness,operationId:b.id(),fence});
const before=b.sourceState({sourceId:input.sourceId});
assert.equal(before.streams.stdout.produced,5);assert.equal(before.streams.stderr.produced,2);
const op=b.id(),args={jobId,reader:early.value,operationId:op,fence};
const observed=await b.call('driver.observeSource',args);
assert.ok(b.verify(observed.value));assert.deepEqual(b.sourceState({sourceId:input.sourceId}).counts,before.counts,'observation causes zero output/client/private/ACK effects');
assert.deepEqual(await b.call('driver.observeSource',args),observed,'same observation ID exact receipt replay');
observed.value.payload.source.streams.stdout.advanced.offset=999;
assert.equal(b.sourceState({sourceId:input.sourceId}).streams.stdout.advanced.offset,5,'returned object never aliases physical source');
const proof=(await b.call('driver.receipt',{operationId:op}));
const guard={observation:proof};
const commit=()=>b.call('store.commit',{operationId:b.id(),fence,writes:[],audit:[],sourceGuards:[guard]});
assert.equal((await commit()).kind,'applied');
b.output(jobId,'stdout',[31]);assert.deepEqual(await commit(),{kind:'not-applied',code:'busy'},'raw source revision guards refuse stale publication');
assert.deepEqual(await b.call('store.commit',{operationId:b.id(),fence,writes:[],audit:[],sourceGuards:[guard,guard]}),{kind:'not-applied',code:'input'});
assert.equal(j.queue[0].key.seq,2);assert.equal(j.queue[0].key.offset,5,'suffix begins after exact source prefix');
b.fault('source-observation.claim','claim',{claim:'negative'});
const claim=await b.call('driver.observeSource',{...args,operationId:b.id()});
assert.equal(claim.value.payload.source.streams.stdout.advanced.offset,-1);assert.ok(b.verify(claim.value),'authentication alone does not approve disclosed incoherent claim');
b.tick(1000);assert.deepEqual(await b.call('store.commit',{operationId:b.id(),fence:{grant:b.grant,deadline:2000},writes:[],audit:[],sourceGuards:[guard]}),{kind:'not-applied',code:'deadline'});
await b.shutdown();console.log('Source initialization, effect-free observations, receipt replay/isolation, revision/deadline guards and signed claim boundary passed.');
