import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {Broker,canonical} from '../benchmarks/recoverable-job-service/private/broker.mjs';
const root='a1'.repeat(32),commitment=createHash('sha256').update(canonical({domain:'rjs-replay-root-v1',root})).digest('hex');
const replayInput={schemaVersion:1,derivationVersion:'rjs-input-hmac-sha256-v1',root,commitment};
const a=new Broker('test',{replayInput,variantId:'B14/base'}),b=new Broker('test',{replayInput:JSON.parse(JSON.stringify(replayInput)),variantId:'B14/base'});
assert.equal(a.scopeId,b.scopeId,'fresh brokers replay exact fixture identity');
assert.deepEqual(a.grant,b.grant,'fresh brokers replay exact authenticated grant bytes');
const first=a.id(),second=b.id();assert.equal(first,second);
await a.call('newId');await a.call('store.scan',{prefix:'extra'});
assert.equal(a.id(),b.id(),'candidate work does not move fixture allocation namespace');
assert.notEqual(await a.call('newId'),a.id(),'independent namespaces preserve uniqueness');
const fence={grant:a.grant,deadline:1000};const r=a.receipt('store.commit',a.scopeId,a.id(),{revision:1},fence);
assert.ok(a.verify(r));assert.ok(b.verify(r),'same replay root authenticates exact corresponding bytes');
assert.ok(!a.verify({...r,payload:{revision:2}}),'changed bytes do not authenticate');
const other=new Broker('test',{replayInput,variantId:'B14/other'});assert.notEqual(other.scopeId,a.scopeId);assert.ok(!other.verify(r),'foreign variant authentication rejected');
assert.throws(()=>new Broker('test',{replayInput:{...replayInput,commitment:'0'.repeat(64)},variantId:'B14/base'}),/commitment/);
assert.equal(a.inputIdentity().rootCommitment,commitment);
assert.notEqual(a.inputIdentity().fixtureCommitment,b.inputIdentity().fixtureCommitment,'actual extra fixture allocation recorded');
await Promise.all([a.shutdown(),b.shutdown(),other.shutdown()]);
console.log('Replay equality, allocation isolation, authenticity, uniqueness and altered commitment rejection passed.');
