import assert from 'node:assert/strict';import {readFile,writeFile} from 'node:fs/promises';
import {evaluateBounded,createReplayInput} from '../benchmarks/recoverable-job-service/private/runtime.mjs';
import {sourceVariants} from '../benchmarks/recoverable-job-service/private/source-cases.mjs';
import {controls} from '../benchmarks/recoverable-job-service/private/controls.mjs';
import {sourceMaterialControl} from '../benchmarks/recoverable-job-service/private/source-controls.mjs';
const source=await readFile('benchmarks/recoverable-job-service/private/reference.js','utf8'),expected=JSON.parse(await readFile('benchmarks/recoverable-job-service/private/control-expectations.json','utf8')),input=createReplayInput(),groups=new Map(),rows=[];
for(const v of sourceVariants.filter(v=>!process.argv[2]||v.id===process.argv[2])){const control=sourceMaterialControl(v);if(!groups.has(control))groups.set(control,[]);groups.get(control).push(v);}
for(const [control,vs]of groups){const options={families:['B17'],variantIds:vs.map(v=>v.id),replayInput:input};const negative=await evaluateBounded(controls[control].mutate(source),options),restored=await evaluateBounded(source,options);for(const v of vs){const n=negative.families[0].variants.find(r=>r.id===v.id),r=restored.families[0].variants.find(r=>r.id===v.id),e=expected[v.id];const passed=negative.status==='valid'&&restored.status==='valid'&&!n.passed&&n.reason.startsWith(e.expectedReasonPrefix)&&n.assertions.some(a=>!a.passed&&a.label.startsWith(e.expectedAssertionPrefix))&&r.passed&&!/Invalid public response|timeout|watchdog/.test(n.reason);rows.push({id:v.id,control,passed,negative:n,restored:r});console.log(v.id,passed?'PASS':'FAIL',n.reason,passed?'':r.reason);}}
const path='.superpowers/sdd/2026-09-08-recoverable-job-service-integration/task-2-material-focused-'+new Date().toISOString().replaceAll(':','-')+'.json';await writeFile(path,JSON.stringify(rows,null,2));console.log(rows.filter(r=>r.passed).length+'/'+rows.length,path);assert.ok(rows.every(r=>r.passed));
